using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    /// <inheritdoc />
    public partial class DefValuesForOrderEntities : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE ""OrderItem"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql(@"ALTER TABLE ""OrderItem"" ALTER COLUMN ""Id"" TYPE text USING ""Id""::text;");
            migrationBuilder.Sql(@"ALTER TABLE ""OrderItem"" ALTER COLUMN ""Id"" SET DEFAULT gen_random_uuid()::text;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE ""OrderItem"" ALTER COLUMN ""Id"" DROP DEFAULT;");
            migrationBuilder.Sql(@"ALTER TABLE ""OrderItem"" ALTER COLUMN ""Id"" TYPE integer USING ""Id""::integer;");
            migrationBuilder.Sql(@"ALTER TABLE ""OrderItem"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
        }
    }
}
